import React, { useState, useEffect } from 'react';
import { ChevronLeft, Shield, Lock, FileText, CheckCircle2, AlertTriangle } from 'lucide-react';
import { Theme } from './types';

interface LegalPageProps {
  type: 'terms' | 'privacy';
  onBack: () => void;
  theme: Theme;
  onCycleTheme: () => void;
  themeIcon: React.ReactNode;
}

const termsContent = [
  {
    id: 'acceptance',
    title: 'Acceptance',
    content: (
      <div className="space-y-4">
        <p>By connecting a repository or using Codeward, you agree to be bound by these Terms of Service. If you are using Codeward on behalf of an organization, you represent that you have the authority to bind them to these Terms.</p>
      </div>
    )
  },
  {
    id: 'definitions',
    title: 'Definitions',
    content: (
      <ul className="space-y-3 list-disc pl-5">
        <li><strong>"Platform"</strong> means the Codeward dashboard, API, and all related services.</li>
        <li><strong>"Agent"</strong> means the autonomous AI systems that analyze, edit, and commit code.</li>
        <li><strong>"Repository"</strong> means the connected codebase environments.</li>
      </ul>
    )
  },
  {
    id: 'account',
    title: 'Account Registration & Access',
    content: (
      <div className="space-y-4">
        <p>You must have the requisite GitHub/Git provider permissions to connect a Repository to the Platform. You are responsible for all actions taken by the Agent within your connected repositories.</p>
      </div>
    )
  },
  {
    id: 'ai-agents',
    title: 'AI Agent Interventions & Code Modifications',
    content: (
      <div className="space-y-4">
        <p>Codeward's agents autonomously generate code, fix bugs, and create Pull Requests.</p>
        <div className="bg-cw-amber/10 border border-cw-amber/30 rounded-xl p-5 flex gap-4 mt-4">
          <AlertTriangle className="text-cw-amber shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-amber mb-1 text-base">AI Autonomy & Responsibility</h4>
            <p className="text-cw-amber/80 text-sm leading-relaxed">
              While we enforce strict security boundaries, you acknowledge that AI-generated code may contain errors. <strong>You are solely responsible for reviewing and approving all Pull Requests generated by Codeward before merging them into production.</strong>
            </p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'data-processing',
    title: 'Data Processing & Security',
    content: (
      <div className="space-y-4">
        <p>We clone your repositories into ephemeral sandboxes to perform analysis.</p>
        <div className="bg-cw-green/10 border border-cw-green/30 rounded-xl p-5 flex gap-4 mt-4">
          <Shield className="text-cw-green shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-green mb-1 text-base">Ephemeral Sandboxes</h4>
            <p className="text-cw-green/80 text-sm leading-relaxed">
              All code analysis is performed in isolated, short-lived microVMs. Once the agent loop completes, the sandbox and all localized source code are immediately destroyed. We do not use your proprietary source code to train our foundational models.
            </p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'limitation',
    title: 'Limitation of Liability',
    content: (
      <div className="space-y-4">
        <div className="bg-cw-red/10 border border-cw-red/30 rounded-xl p-5 flex gap-4 mt-4">
          <AlertTriangle className="text-cw-red shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-red mb-1 text-base">Disclaimer of Warranties</h4>
            <p className="text-cw-red/80 text-sm leading-relaxed">
              Codeward is provided "AS IS". We are not liable for any direct, indirect, or incidental damages, including data loss, system outages, or security breaches resulting from the merger of AI-generated code.
            </p>
          </div>
        </div>
      </div>
    )
  }
];

const privacyContent = [
  {
    id: 'information-collected',
    title: 'Information We Collect',
    content: (
      <div className="space-y-4">
        <p>We collect account information (email, name, organization) and repository metadata (commit history, branch names, PR discussions).</p>
      </div>
    )
  },
  {
    id: 'source-code',
    title: 'Handling of Source Code',
    content: (
      <div className="space-y-4">
        <div className="bg-cw-green/10 border border-cw-green/30 rounded-xl p-5 flex gap-4 mt-4">
          <Lock className="text-cw-green shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-green mb-1 text-base">Zero-Retention Code Processing</h4>
            <p className="text-cw-green/80 text-sm leading-relaxed">
              Your source code is strictly used for the duration of an active agent run. We read the files necessary to resolve your technical debt or feature requests, and we discard the local copies immediately upon run completion. Your code is never stored in our permanent databases.
            </p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'third-party',
    title: 'Third-Party AI Providers',
    content: (
      <div className="space-y-4">
        <div className="bg-cw-amber/10 border border-cw-amber/30 rounded-xl p-5 flex gap-4 mt-4">
          <Shield className="text-cw-amber shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-amber mb-1 text-base">Sub-processors</h4>
            <p className="text-cw-amber/80 text-sm leading-relaxed">
              To power our agents, portions of your codebase (specifically, files requested by the agent) are sent to third-party LLM providers (e.g., OpenAI, Anthropic) via API. We maintain strict Data Processing Agreements with these providers ensuring zero-retention policies and explicitly prohibiting the use of your data for model training.
            </p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'how-we-use',
    title: 'How We Use Your Data',
    content: (
      <div className="space-y-4">
        <p>We use your telemetry and run-state metadata (but not your source code) to improve our orchestrator routing, fix platform bugs, and track autonomous agent success rates.</p>
      </div>
    )
  },
  {
    id: 'your-rights',
    title: 'Your Rights',
    content: (
      <div className="space-y-4">
        <p>You may disconnect your repositories at any time, which instantly revokes all access tokens and halts all agent activities. You may also request the deletion of your Codeward account and associated metadata by contacting support.</p>
      </div>
    )
  }
];

export function LegalPage({ type, onBack, theme, onCycleTheme, themeIcon }: LegalPageProps) {
  const isTerms = type === 'terms';
  const content = isTerms ? termsContent : privacyContent;
  const title = isTerms ? 'Terms of Service' : 'Privacy Policy';
  const date = 'Effective Date: October 2026';

  const [activeSection, setActiveSection] = useState(content[0].id);

  // Simple scroll spy logic
  useEffect(() => {
    const handleScroll = () => {
      const sections = content.map(c => document.getElementById(c.id));
      let currentActive = content[0].id;
      
      for (const section of sections) {
        if (section) {
          const rect = section.getBoundingClientRect();
          // Adjust offset to trigger active state nicely
          if (rect.top <= 150) {
            currentActive = section.id;
          }
        }
      }
      setActiveSection(currentActive);
    };

    const container = document.getElementById('scroll-container');
    if (container) {
      container.addEventListener('scroll', handleScroll);
      return () => container.removeEventListener('scroll', handleScroll);
    }
  }, [content]);

  const scrollTo = (id: string) => {
    const el = document.getElementById(id);
    const container = document.getElementById('scroll-container');
    if (el && container) {
      const topPos = el.offsetTop - 100;
      container.scrollTo({ top: topPos, behavior: 'smooth' });
    }
  };

  return (
    <div className={`theme-${theme} w-full h-screen flex flex-col bg-cw-bg transition-colors duration-300 font-sans text-cw-txt`}>
      {/* Top Navigation */}
      <div className="h-[80px] border-b border-cw-bdr px-8 flex items-center justify-between shrink-0 bg-cw-bg z-10 relative">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-cw-txt2 hover:text-cw-txt transition-colors font-medium text-[13px]"
        >
          <ChevronLeft size={16} />
          Back
        </button>
        <button 
          onClick={onCycleTheme} 
          className="w-9 h-9 rounded-full border border-cw-bdr bg-cw-bg2 text-cw-txt2 flex items-center justify-center hover:bg-cw-bg3 transition-colors"
        >
          {themeIcon}
        </button>
      </div>

      {/* Main Container */}
      <div id="scroll-container" className="flex-1 overflow-y-auto overflow-x-hidden scroll-smooth relative">
        <div className="max-w-[1000px] mx-auto px-8 py-16 flex flex-col md:flex-row gap-16">
          
          {/* Left Sidebar (Table of Contents) */}
          <div className="w-[280px] shrink-0 hidden md:block relative">
            <div className="sticky top-[40px] border border-cw-bdr bg-cw-bg2 rounded-2xl p-6 shadow-sm">
              <h3 className="font-bold text-cw-txt mb-6 text-[15px]">Table of Contents</h3>
              <ul className="space-y-4">
                {content.map((section, idx) => (
                  <li key={section.id}>
                    <button 
                      onClick={() => scrollTo(section.id)}
                      className={`text-left w-full flex items-center gap-3 text-[13px] font-medium transition-colors ${
                        activeSection === section.id ? 'text-cw-blue' : 'text-cw-txt2 hover:text-cw-txt'
                      }`}
                    >
                      <span className="w-5 font-semibold opacity-50 text-right">{idx + 1}</span>
                      <span className="truncate">{section.title}</span>
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Right Content */}
          <div className="flex-1 max-w-[650px]">
            <div className="mb-16">
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-cw-red/10 text-cw-red font-semibold text-[11px] uppercase tracking-wider mb-6">
                <FileText size={14} />
                {title}
              </div>
              <h1 className="text-[40px] leading-[1.1] font-bold text-cw-txt tracking-tight mb-6">{title}</h1>
              <p className="text-cw-txt2 text-[15px] leading-relaxed">
                {date} · {isTerms ? 'These Terms form a binding legal agreement between you and Codeward. Please read them carefully before using the platform.' : 'This Privacy Policy explains how we collect, use, and handle your source code and data.'}
              </p>
            </div>

            <div className="space-y-12 pb-32">
              {content.map((section, idx) => (
                <section key={section.id} id={section.id} className="relative pt-6">
                  {/* Divider */}
                  {idx > 0 && <div className="absolute top-0 left-0 right-0 h-px bg-cw-bdr" />}
                  
                  <div className="flex gap-6 mt-8">
                    {/* Number Badge */}
                    <div className="w-8 h-8 rounded-full bg-cw-red/10 text-cw-red flex items-center justify-center shrink-0 font-bold text-sm shadow-sm border border-cw-red/20 mt-0.5">
                      {idx + 1}
                    </div>
                    
                    {/* Section Body */}
                    <div className="flex-1">
                      <h2 className="text-[20px] font-bold text-cw-txt mb-4">{section.title}</h2>
                      <div className="text-cw-txt2 text-[14px] leading-[1.8]">
                        {section.content}
                      </div>
                    </div>
                  </div>
                </section>
              ))}
            </div>
          </div>
          
        </div>
      </div>
    </div>
  );
}
