import React from 'react';
import { Shield, Lock, FileText, CheckCircle2, AlertTriangle } from 'lucide-react';

export const termsContent = [
  {
    id: 'acceptance-binding-effect',
    title: '1. Acceptance & Binding Effect',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">1.1</div>
          <div className="leading-relaxed text-[14px]">By creating an account, connecting a Repository, initiating an Agent run, or otherwise accessing any part of the Platform, you confirm that you have read, understood, and agree to be legally bound by these Terms in their entirety.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">1.2</div>
          <div className="leading-relaxed text-[14px]">If you are accepting on behalf of a company, partnership, or other legal entity ("Organization"), you represent and warrant that you have full legal authority to bind that Organization to these Terms. In such case, "you" and "User" refer to that Organization and all its Authorized Users.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">1.3</div>
          <div className="leading-relaxed text-[14px]">If you do not agree with any provision of these Terms, you must immediately cease all use of the Platform and close your account. Continued use after the Effective Date of any updated Terms constitutes acceptance of those updates.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">1.4</div>
          <div className="leading-relaxed text-[14px]">These Terms apply in addition to any Order Form, Statement of Work, Enterprise Agreement, or Data Processing Agreement executed between the parties. In the event of conflict, the Order Form or Enterprise Agreement shall prevail to the extent of that conflict.</div>
        </div>
        <div className="bg-cw-amber/10 border border-cw-amber/30 rounded-xl p-5 flex gap-4 mt-6 mb-2">
          <AlertTriangle className="text-cw-amber shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-amber mb-1 text-base">Minimum Age Requirement.</h4>
            <p className="text-cw-amber/80 text-sm leading-relaxed">You must be at least 18 years of age and legally capable of entering into binding contracts in your jurisdiction. Use of the Platform by persons under 18 is strictly prohibited.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'definitions',
    title: '2. Definitions',
    content: (
      <div className="space-y-4">
        <p className="leading-relaxed text-[14px]">In these Terms, the following capitalised terms have the meanings set out below:</p>
        <div className="mt-6 mb-4 border border-cw-bdr rounded-xl overflow-hidden">
          <div className="bg-cw-bg2 px-4 py-3 border-b border-cw-bdr text-xs font-bold tracking-wider uppercase">Defined Terms</div>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="bg-cw-bg">
                <tr>
                  <th className="px-4 py-3 font-semibold border-b border-cw-bdr">Term</th>
                  <th className="px-4 py-3 font-semibold border-b border-cw-bdr">Meaning</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-cw-bdr">
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Agent"</strong></td>
                  <td className="px-4 py-3 align-top ">Any autonomous or semi-autonomous AI system operated by Codeward that reads, analyses, modifies, or comments on code, including the Orchestrator, Guardian, and Analyzer Agents.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Agent Output"</strong></td>
                  <td className="px-4 py-3 align-top ">Any Pull Request, inline comment, code suggestion, security report, score, decision, or other artefact generated by an Agent.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Authorized User"</strong></td>
                  <td className="px-4 py-3 align-top ">An individual employee, contractor, or representative permitted by the User to access the Platform under the User's account credentials.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Confidential Information"</strong></td>
                  <td className="px-4 py-3 align-top ">Source code, architecture diagrams, credentials, business logic, and any non-public technical or commercial information disclosed by either party.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Ephemeral Sandbox"</strong></td>
                  <td className="px-4 py-3 align-top ">An isolated, short-lived virtual machine environment created solely for a single Agent run and destroyed immediately upon completion.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Foundational Model"</strong></td>
                  <td className="px-4 py-3 align-top ">Third-party large language models (e.g., GPT-4o, Claude) used by Agents to perform analysis and generate outputs.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Gate Decision"</strong></td>
                  <td className="px-4 py-3 align-top ">The Orchestrator Agent's final PASS or BLOCK verdict on a Pull Request, based on aggregated Analyzer Agent reports.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Platform"</strong></td>
                  <td className="px-4 py-3 align-top ">The Codeward web dashboard, REST and webhook APIs, Agent infrastructure, CI/CD integrations, and all associated services.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Repository"</strong></td>
                  <td className="px-4 py-3 align-top ">A version-controlled codebase connected to the Platform by the User via GitHub, GitLab, Bitbucket, or other supported Git providers.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Run"</strong></td>
                  <td className="px-4 py-3 align-top ">A single execution cycle initiated by a commit, Pull Request event, or manual trigger, resulting in Agent analysis and a Gate Decision.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"Subscription"</strong></td>
                  <td className="px-4 py-3 align-top ">The paid or free-tier access plan selected by the User, as described on Codeward's pricing page.</td>
                </tr>
                <tr className="hover:bg-cw-bg2/50 transition-colors">
                  <td className="px-4 py-3 align-top "><strong>"User Data"</strong></td>
                  <td className="px-4 py-3 align-top ">Source code, commit history, configuration files, and any other data submitted by the User to the Platform during a Run.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'account-registration-access',
    title: '3. Account Registration & Access',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">3.1</div>
          <div className="leading-relaxed text-[14px]">Eligibility. To register, you must provide accurate, current, and complete information. You must notify Codeward immediately of any change to that information. Codeward may suspend accounts where registration details are found to be false or misleading.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">3.2</div>
          <div className="leading-relaxed text-[14px]">Credential Security. You are solely responsible for maintaining the confidentiality of your account credentials, API keys, and OAuth tokens. You must not share credentials between Authorized Users. Any activity conducted under your credentials is your sole responsibility, whether authorised by you or not.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">3.3</div>
          <div className="leading-relaxed text-[14px]">Repository Permissions. By connecting a Repository, you represent that you hold or have been granted sufficient permissions (including repository admin rights) to authorise Codeward to clone, read, analyse, and post comments and Pull Request reviews to that Repository.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">3.4</div>
          <div className="leading-relaxed text-[14px]">Authorized Users. You may grant access to Authorized Users up to the limit specified in your Subscription plan. You are responsible for ensuring all Authorized Users comply with these Terms. Any breach by an Authorized User is treated as a breach by the User.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">3.5</div>
          <div className="leading-relaxed text-[14px]">Account Integrity. You must not create multiple accounts to circumvent usage limits, access suspended features, or obtain free-tier benefits beyond their intended scope.</div>
        </div>
      </div>
    )
  },
  {
    id: 'permitted-use-restrictions',
    title: '4. Permitted Use & Restrictions',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">4.1</div>
          <div className="leading-relaxed text-[14px]">Permitted Use. Subject to these Terms and your Subscription, Codeward grants you a limited, non-exclusive, non-transferable, revocable licence to access and use the Platform solely for your internal software development and quality assurance purposes.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">4.2</div>
          <div className="leading-relaxed text-[14px]">Prohibited Conduct. You must not, and must ensure your Authorized Users do not:</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(a)</div>
          <div className="leading-relaxed text-[14px]">Attempt to reverse-engineer, decompile, disassemble, or derive source code from the Platform or any Agent;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(b)</div>
          <div className="leading-relaxed text-[14px]">Use the Platform to analyse, train on, or benchmark third-party codebases without the right to do so;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(c)</div>
          <div className="leading-relaxed text-[14px]">Inject malicious code, prompt injection payloads, adversarial inputs, or any data designed to manipulate, confuse, or compromise Agent behaviour;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(d)</div>
          <div className="leading-relaxed text-[14px]">Resell, sublicense, or make the Platform available to third parties as a standalone service without a written white-label agreement with Codeward;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(e)</div>
          <div className="leading-relaxed text-[14px]">Use the Platform to process Repositories containing malware, ransomware, exploit code, or any software designed to cause harm to third-party systems;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(f)</div>
          <div className="leading-relaxed text-[14px]">Circumvent, disable, or interfere with any rate limits, security controls, sandbox boundaries, or access controls;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(g)</div>
          <div className="leading-relaxed text-[14px]">Use the Platform in violation of any applicable law, regulation, or export control regime, including the EU AI Act (2024), Kenya's Data Protection Act (2019), or equivalent legislation in your jurisdiction.</div>
        </div>
        <div className="bg-cw-red/10 border border-cw-red/30 rounded-xl p-5 flex gap-4 mt-6 mb-2">
          <AlertTriangle className="text-cw-red shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-red mb-1 text-base">Zero Tolerance.</h4>
            <p className="text-cw-red/80 text-sm leading-relaxed">Any attempt to manipulate Agent decisions through adversarial inputs, prompt injection, or Repository tampering will result in immediate account termination and may be referred to law enforcement authorities.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'ai-agent-operations-code-modifications',
    title: '5. AI Agent Operations & Code Modifications',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">5.1</div>
          <div className="leading-relaxed text-[14px]">Nature of Agent Operations. The Platform operates a multi-agent pipeline. Upon a trigger event (e.g., a Pull Request), the Orchestrator Agent clones the Repository into an Ephemeral Sandbox, dispatches Analyzer Agents (covering security, architecture, performance, bloat, testing, documentation, dependencies, and code style), aggregates their findings, and issues a Gate Decision. The Guardian Agent then communicates findings to your development team via GitHub comments and Pull Request reviews.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">5.2</div>
          <div className="leading-relaxed text-[14px]">Gate Decisions. A BLOCK Gate Decision will cause the Platform to formally request changes on the Pull Request via your connected Git provider. A PASS decision will trigger a formal approval. These actions are automated and are taken on behalf of the Authorized User who configured the integration.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">5.3</div>
          <div className="leading-relaxed text-[14px]">User Responsibility for Merges. Notwithstanding any Gate Decision, you are solely and entirely responsible for all code merged into your Repository. A PASS Gate Decision is an automated quality signal, not a guarantee of correctness, security, or fitness for purpose. You must maintain human review processes appropriate to your risk profile. Codeward's Gate Decision does not relieve you of your engineering obligations.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">5.4</div>
          <div className="leading-relaxed text-[14px]">AI Inherent Limitations. You acknowledge that:</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(a)</div>
          <div className="leading-relaxed text-[14px]">Agent Outputs are generated by probabilistic Foundational Models and may contain errors, false positives, false negatives, or incomplete analysis;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(b)</div>
          <div className="leading-relaxed text-[14px]">Agents do not have full semantic understanding of your business logic, domain context, or deployment environment;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(c)</div>
          <div className="leading-relaxed text-[14px]">Security findings issued by the Security Analyzer Agent are indicative, not exhaustive, and do not constitute a penetration test or formal security audit;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(d)</div>
          <div className="leading-relaxed text-[14px]">Agent behaviour may vary across Runs due to the non-deterministic nature of Foundational Models.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">5.5</div>
          <div className="leading-relaxed text-[14px]">No Training on User Data. Codeward does not use your source code, Agent Outputs, or any User Data to fine-tune, retrain, or otherwise improve any Foundational Model. This prohibition applies to both first-party models and any third-party model providers engaged by Codeward.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">5.6</div>
          <div className="leading-relaxed text-[14px]">Agent Configuration. Users on eligible Subscription tiers may configure Agent sensitivity thresholds, blocked file patterns, and custom rulesets. Codeward is not liable for Gate Decisions that result from misconfigured user-defined rules.</div>
        </div>
        <div className="bg-cw-blue/10 border border-cw-blue/30 rounded-xl p-5 flex gap-4 mt-6 mb-2">
          <CheckCircle2 className="text-cw-blue shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-blue mb-1 text-base">Human Oversight Requirement.</h4>
            <p className="text-cw-blue/80 text-sm leading-relaxed">In regulated industries (financial services, healthcare, critical infrastructure, government systems), you are required by applicable law and these Terms to maintain mandatory human review of all Agent Outputs before acting on them. Codeward's platform is a tool, not a replacement for professional engineering judgment.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'data-processing-privacy-security',
    title: '6. Data Processing, Privacy & Security',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">6.1</div>
          <div className="leading-relaxed text-[14px]">Ephemeral Sandbox Architecture. All code analysis is performed inside isolated Ephemeral Sandboxes. Each Sandbox is a single-use microVM created for one Run. Upon completion of the Agent loop, the Sandbox and all cloned source code are cryptographically wiped and destroyed within 60 seconds of Run completion. No source code persists on Codeward infrastructure beyond the duration of a Run.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">6.2</div>
          <div className="leading-relaxed text-[14px]">Data Retained. Codeward retains only the following post-Run data, stored in encrypted form:</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(a)</div>
          <div className="leading-relaxed text-[14px]">Agent findings and Gate Decision results (structured JSON), for your dashboard history;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(b)</div>
          <div className="leading-relaxed text-[14px]">Run metadata (timestamp, repository name, commit SHA, duration, score);</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(c)</div>
          <div className="leading-relaxed text-[14px]">Anonymised aggregate metrics used for Platform performance monitoring (no source code or business logic).</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">6.3</div>
          <div className="leading-relaxed text-[14px]">Third-Party Model Providers. Source code excerpts (code snippets relevant to a specific finding, not full files) may be transmitted to third-party Foundational Model providers (currently OpenAI, Inc.) for inference purposes. These providers are bound by data processing agreements prohibiting training on customer data. You consent to this transmission by using the Platform.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">6.4</div>
          <div className="leading-relaxed text-[14px]">Personal Data. To the extent User Data contains personal data as defined under applicable data protection law (including Kenya's Data Protection Act 2019, the EU GDPR, or equivalent), Codeward processes such data as a data processor acting on your instructions. The Data Processing Addendum at Schedule B governs such processing.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">6.5</div>
          <div className="leading-relaxed text-[14px]">Security Standards. Codeward implements the following technical and organisational security measures:</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(a)</div>
          <div className="leading-relaxed text-[14px]">AES-256 encryption for all data at rest;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(b)</div>
          <div className="leading-relaxed text-[14px]">TLS 1.3 for all data in transit;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(c)</div>
          <div className="leading-relaxed text-[14px]">Network-isolated Sandbox environments with no outbound internet access during Runs;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(d)</div>
          <div className="leading-relaxed text-[14px]">Role-based access controls and audit logging for all Platform infrastructure access;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(e)</div>
          <div className="leading-relaxed text-[14px]">Vulnerability disclosure programme and regular third-party penetration testing (annual minimum).</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">6.6</div>
          <div className="leading-relaxed text-[14px]">Incident Notification. In the event of a confirmed security incident affecting your User Data, Codeward will notify you within 72 hours of becoming aware of the incident, consistent with applicable data breach notification obligations.</div>
        </div>
        <div className="bg-cw-amber/10 border border-cw-amber/30 rounded-xl p-5 flex gap-4 mt-6 mb-2">
          <AlertTriangle className="text-cw-amber shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-amber mb-1 text-base">Third-Party Model Transmission.</h4>
            <p className="text-cw-amber/80 text-sm leading-relaxed">If your Repository contains classified, export-controlled, or government-classified source code, you must not connect it to the Platform without first obtaining a written waiver from Codeward confirming an on-premises or air-gapped deployment arrangement.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'intellectual-property',
    title: '7. Intellectual Property',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">7.1</div>
          <div className="leading-relaxed text-[14px]">User Ownership. You retain all intellectual property rights in your source code, Repositories, and User Data. Nothing in these Terms transfers any ownership of your code to Codeward.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">7.2</div>
          <div className="leading-relaxed text-[14px]">Licence to Codeward. You grant Codeward a limited, non-exclusive, royalty-free licence to access, clone, process, and transmit your User Data solely to the extent necessary to provide the Platform services during the term of your Subscription. This licence terminates upon account closure.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">7.3</div>
          <div className="leading-relaxed text-[14px]">Agent Output Ownership. Agent Outputs (Pull Request comments, findings reports, Gate Decisions) are generated on your behalf. You own the Agent Outputs associated with your Runs. Codeward retains no proprietary claim over the substance of those outputs.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">7.4</div>
          <div className="leading-relaxed text-[14px]">Platform IP. All rights in the Platform, including the multi-agent orchestration architecture, scoring algorithms, Agent prompts, and the Codeward brand, are owned exclusively by Codeward or its licensors. These Terms grant no ownership rights in Platform IP.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">7.5</div>
          <div className="leading-relaxed text-[14px]">Feedback. If you provide suggestions, bug reports, or feature requests ("Feedback"), you grant Codeward a perpetual, irrevocable, royalty-free licence to use that Feedback to improve the Platform without any obligation or compensation to you.</div>
        </div>
      </div>
    )
  },
  {
    id: 'subscription-billing-payments',
    title: '8. Subscription, Billing & Payments',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">8.1</div>
          <div className="leading-relaxed text-[14px]">Subscription Tiers. Codeward offers tiered Subscription plans (including a free Developer tier and paid Team, Business, and Enterprise tiers). Features, Run limits, Authorized User counts, and SLA commitments vary by tier as published on the pricing page.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">8.2</div>
          <div className="leading-relaxed text-[14px]">Billing Cycle. Paid Subscriptions are billed monthly or annually in advance. All fees are stated in USD unless an Order Form specifies otherwise. Fees are non-refundable except as expressly stated in clause 8.5.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">8.3</div>
          <div className="leading-relaxed text-[14px]">Automatic Renewal. Subscriptions renew automatically at the end of each billing period unless cancelled at least 5 business days before the renewal date via the account dashboard. You authorise Codeward to charge the payment method on file for each renewal.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">8.4</div>
          <div className="leading-relaxed text-[14px]">Failed Payments. If a payment fails, Codeward will attempt to re-charge the payment method up to three times over 7 days. If payment remains outstanding after 7 days, the account will be downgraded to the free tier and Run history will be placed in read-only mode pending settlement.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">8.5</div>
          <div className="leading-relaxed text-[14px]">Refunds. Codeward will issue a pro-rata refund for the unused portion of a paid annual Subscription if you cancel within 30 days of the initial purchase or annual renewal date. No refunds are issued for monthly Subscriptions or for accounts suspended due to Terms violations.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">8.6</div>
          <div className="leading-relaxed text-[14px]">Price Changes. Codeward may revise Subscription pricing with 60 days' written notice to existing subscribers. Price changes do not apply to the current billing period and take effect at the next renewal date after the notice period.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">8.7</div>
          <div className="leading-relaxed text-[14px]">Taxes. All fees are exclusive of applicable taxes, levies, and duties. You are responsible for all taxes applicable to your Subscription in your jurisdiction. Where Codeward is required by law to collect such taxes, they will be added to the invoice.</div>
        </div>
      </div>
    )
  },
  {
    id: 'service-levels-availability',
    title: '9. Service Levels & Availability',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">9.1</div>
          <div className="leading-relaxed text-[14px]">Uptime Target. Codeward targets 99.5% monthly Platform availability for paid Subscription tiers. Availability is measured excluding Scheduled Maintenance windows and Force Majeure events.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">9.2</div>
          <div className="leading-relaxed text-[14px]">Scheduled Maintenance. Codeward will provide at least 48 hours' notice of Scheduled Maintenance windows. Maintenance will be conducted during low-traffic periods (weekends, 00:00–06:00 UTC where possible).</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">9.3</div>
          <div className="leading-relaxed text-[14px]">Service Credits. If monthly availability falls below 99.5% in any calendar month (excluding events in 9.2), Business and Enterprise tier subscribers may claim a service credit equal to 10% of their monthly fee for each full percentage point below the target. Total credits shall not exceed 30% of monthly fees. Credits are the sole remedy for availability failures.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">9.4</div>
          <div className="leading-relaxed text-[14px]">Third-Party Dependencies. Platform availability may be affected by third-party services including GitHub, GitLab, OpenAI API, and cloud infrastructure providers. Downtime attributable to these third parties does not constitute a breach of Codeward's availability obligations.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">9.5</div>
          <div className="leading-relaxed text-[14px]">Free Tier. The free Developer tier is provided on a best-efforts basis with no uptime commitment and no service credits.</div>
        </div>
      </div>
    )
  },
  {
    id: 'confidentiality',
    title: '10. Confidentiality',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">10.1</div>
          <div className="leading-relaxed text-[14px]">Mutual Obligation. Each party agrees to hold the other party's Confidential Information in strict confidence, using at least the same degree of care it uses to protect its own confidential information, but in no case less than reasonable care.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">10.2</div>
          <div className="leading-relaxed text-[14px]">Permitted Disclosures. Confidential Information may be disclosed only to employees, contractors, and agents who have a need to know for the purposes of these Terms and who are bound by confidentiality obligations no less protective than those herein.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">10.3</div>
          <div className="leading-relaxed text-[14px]">Exclusions. Confidentiality obligations do not apply to information that: (a) is or becomes publicly known through no breach of these Terms; (b) was independently developed without reference to Confidential Information; (c) is required to be disclosed by law, court order, or regulatory authority, provided the disclosing party gives prompt written notice to the other party where legally permissible.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">10.4</div>
          <div className="leading-relaxed text-[14px]">Survival. Confidentiality obligations survive termination of these Terms for a period of 5 years, except with respect to trade secrets, which shall be protected for as long as they remain trade secrets under applicable law.</div>
        </div>
      </div>
    )
  },
  {
    id: 'representations-warranties',
    title: '11. Representations & Warranties',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">11.1</div>
          <div className="leading-relaxed text-[14px]">User Warranties. You represent and warrant that:</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(a)</div>
          <div className="leading-relaxed text-[14px]">You have the legal right, authority, and all necessary permissions to connect each Repository to the Platform;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(b)</div>
          <div className="leading-relaxed text-[14px]">Your use of the Platform will comply with all applicable laws and regulations;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(c)</div>
          <div className="leading-relaxed text-[14px]">Your User Data does not infringe the intellectual property rights of any third party;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(d)</div>
          <div className="leading-relaxed text-[14px]">You will not introduce data into the Platform designed to cause harm to Codeward's infrastructure or other users.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">11.2</div>
          <div className="leading-relaxed text-[14px]">Codeward Warranties. Codeward warrants that it will provide the Platform with reasonable skill and care consistent with generally accepted industry standards for AI-assisted developer tooling.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">11.3</div>
          <div className="leading-relaxed text-[14px]">Disclaimer. Except as expressly stated in clause 11.2, the Platform and all Agent Outputs are provided "AS IS" and "AS AVAILABLE". Codeward expressly disclaims all implied warranties, including warranties of merchantability, fitness for a particular purpose, accuracy, and non-infringement. Codeward does not warrant that Agent Outputs will be error-free or that the Platform will meet your specific requirements.</div>
        </div>
      </div>
    )
  },
  {
    id: 'indemnification',
    title: '12. Indemnification',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">12.1</div>
          <div className="leading-relaxed text-[14px]">User Indemnity. You agree to defend, indemnify, and hold harmless Codeward, its officers, directors, employees, and agents from and against any claims, damages, losses, liabilities, and expenses (including reasonable legal fees) arising out of or relating to:</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(a)</div>
          <div className="leading-relaxed text-[14px]">Your breach of any provision of these Terms;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(b)</div>
          <div className="leading-relaxed text-[14px]">Your use of the Platform in violation of applicable law;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(c)</div>
          <div className="leading-relaxed text-[14px]">Any claim that your User Data or source code infringes a third party's intellectual property rights;</div>
        </div>
        <div className="flex gap-4 pl-12">
          <div className="text-cw-txt2 shrink-0 pt-0.5 w-6">(d)</div>
          <div className="leading-relaxed text-[14px]">Any production incident, data breach, or system failure resulting from code merged by you after a PASS Gate Decision.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">12.2</div>
          <div className="leading-relaxed text-[14px]">Codeward Indemnity. Codeward will defend you against any third-party claim that the Platform (excluding User Data) directly infringes a valid patent, copyright, or trade secret, provided you promptly notify Codeward in writing and grant Codeward sole control of the defence.</div>
        </div>
      </div>
    )
  },
  {
    id: 'limitation-of-liability',
    title: '13. Limitation of Liability',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">13.1</div>
          <div className="leading-relaxed text-[14px]">Exclusion of Consequential Loss. To the maximum extent permitted by applicable law, Codeward shall not be liable for any indirect, incidental, special, consequential, punitive, or exemplary damages, including but not limited to: loss of profits, loss of revenue, loss of data, loss of business opportunity, production outages, or reputational harm — regardless of whether such damages were foreseeable or Codeward had been advised of their possibility.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">13.2</div>
          <div className="leading-relaxed text-[14px]">Aggregate Cap. Codeward's total aggregate liability to you under or in connection with these Terms, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, shall not exceed the greater of: (a) the total fees paid by you to Codeward in the 12 months immediately preceding the event giving rise to the claim; or (b) USD 500.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">13.3</div>
          <div className="leading-relaxed text-[14px]">Essential Basis. You acknowledge that the limitations in clauses 13.1 and 13.2 reflect a reasonable allocation of risk between the parties and are an essential basis of the bargain between the parties. Codeward would not have entered into these Terms without these limitations.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">13.4</div>
          <div className="leading-relaxed text-[14px]">Exceptions. Nothing in these Terms limits either party's liability for: (a) death or personal injury caused by negligence; (b) fraud or fraudulent misrepresentation; (c) any liability that cannot be limited or excluded by applicable law.</div>
        </div>
        <div className="bg-cw-red/10 border border-cw-red/30 rounded-xl p-5 flex gap-4 mt-6 mb-2">
          <AlertTriangle className="text-cw-red shrink-0" size={24} />
          <div>
            <h4 className="font-semibold text-cw-red mb-1 text-base">Critical Production Systems.</h4>
            <p className="text-cw-red/80 text-sm leading-relaxed">You must not rely solely on Agent Gate Decisions as the final approval mechanism for code deployments to safety-critical, life-critical, or mission-critical production systems. In such environments, mandatory human senior engineering review is required prior to any merge. Codeward accepts no liability for harms arising from deployment of Agent-reviewed code to such systems.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'suspension-termination',
    title: '14. Suspension & Termination',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">14.1</div>
          <div className="leading-relaxed text-[14px]">Termination by User. You may terminate your Subscription at any time via the account dashboard. Termination takes effect at the end of the current billing period. You remain responsible for all fees accrued prior to termination.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">14.2</div>
          <div className="leading-relaxed text-[14px]">Termination by Codeward for Cause. Codeward may terminate your account immediately upon written notice if: (a) you materially breach these Terms and fail to remedy the breach within 14 days of notice; (b) you engage in any conduct described in clause 4.2; (c) you become insolvent or make an assignment for the benefit of creditors.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">14.3</div>
          <div className="leading-relaxed text-[14px]">Suspension. Codeward may suspend access to the Platform without notice where: (a) there is a credible security threat; (b) your usage is causing material harm to Platform infrastructure or other users; (c) a payment is more than 14 days overdue.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">14.4</div>
          <div className="leading-relaxed text-[14px]">Effect of Termination. Upon termination, your licence to use the Platform ceases immediately. Codeward will delete your Run history and retained Agent findings within 90 days of termination, subject to any legal hold obligations. Clauses 7, 10, 12, 13, and 15 survive termination.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">14.5</div>
          <div className="leading-relaxed text-[14px]">Data Export. Prior to account closure, you may export your Run history and findings via the dashboard export feature. Codeward is not obligated to retain or provide your data after the 90-day deletion window.</div>
        </div>
      </div>
    )
  },
  {
    id: 'dispute-resolution-governing-law',
    title: '15. Dispute Resolution & Governing Law',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">15.1</div>
          <div className="leading-relaxed text-[14px]">Governing Law. These Terms shall be governed by and construed in accordance with the laws of [JURISDICTION — e.g., Kenya / England & Wales / Delaware], without regard to its conflict of law provisions.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">15.2</div>
          <div className="leading-relaxed text-[14px]">Escalation Process. Before initiating formal proceedings, the parties agree to attempt good-faith resolution by escalating the dispute to senior management of each party. The escalation period is 30 days from written notice of the dispute.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">15.3</div>
          <div className="leading-relaxed text-[14px]">Arbitration. If the dispute is not resolved within the escalation period, it shall be finally resolved by binding arbitration under the rules of [NAIROBI CENTRE FOR INTERNATIONAL ARBITRATION / ICC / LCIA], with proceedings conducted in [CITY] in the English language. The arbitral award shall be final and enforceable in any competent court.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">15.4</div>
          <div className="leading-relaxed text-[14px]">Injunctive Relief. Nothing in this clause prevents either party from seeking urgent injunctive or other equitable relief from a court of competent jurisdiction to prevent irreparable harm pending arbitration.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">15.5</div>
          <div className="leading-relaxed text-[14px]">Class Action Waiver. All disputes must be brought in an individual capacity. Neither party may participate in a class action, collective arbitration, or representative proceeding in connection with these Terms.</div>
        </div>
      </div>
    )
  },
  {
    id: 'changes-to-terms',
    title: '16. Changes to Terms',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">16.1</div>
          <div className="leading-relaxed text-[14px]">Codeward may update these Terms at any time. For material changes, Codeward will provide at least 30 days' notice by email to your registered address and/or a prominent in-app notification. The updated Terms will be posted at codeward.dev/legal/terms with the revised Effective Date.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">16.2</div>
          <div className="leading-relaxed text-[14px]">Your continued use of the Platform after the effective date of any revision constitutes your acceptance of the revised Terms. If you object to a material change, your sole remedy is to terminate your Subscription before the change takes effect.</div>
        </div>
      </div>
    )
  },
  {
    id: 'general-provisions',
    title: '17. General Provisions',
    content: (
      <div className="space-y-4">
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">17.1</div>
          <div className="leading-relaxed text-[14px]">Entire Agreement. These Terms, together with any applicable Order Form, Schedule, or Enterprise Agreement, constitute the entire agreement between the parties regarding the Platform and supersede all prior representations, negotiations, and agreements.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">17.2</div>
          <div className="leading-relaxed text-[14px]">Severability. If any provision of these Terms is held to be invalid or unenforceable, that provision shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">17.3</div>
          <div className="leading-relaxed text-[14px]">Waiver. No failure or delay by either party to exercise any right under these Terms operates as a waiver. A waiver of any specific breach does not constitute a waiver of future breaches.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">17.4</div>
          <div className="leading-relaxed text-[14px]">Assignment. You may not assign or transfer any rights or obligations under these Terms without Codeward's prior written consent. Codeward may assign these Terms in connection with a merger, acquisition, or sale of substantially all of its assets, upon 30 days' notice to you.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">17.5</div>
          <div className="leading-relaxed text-[14px]">Force Majeure. Neither party shall be liable for failure to perform obligations under these Terms to the extent caused by events beyond reasonable control, including natural disasters, acts of government, internet infrastructure failures, cyberattacks on third-party providers, or pandemics — provided the affected party gives prompt written notice and uses reasonable efforts to mitigate the impact.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">17.6</div>
          <div className="leading-relaxed text-[14px]">Notices. Legal notices under these Terms must be in writing and delivered by email with read receipt to legal@codeward.dev (for Codeward) or to the email address on your registered account (for you). Notices are effective upon confirmed delivery.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">17.7</div>
          <div className="leading-relaxed text-[14px]">Independent Contractors. The parties are independent contractors. Nothing in these Terms creates any partnership, joint venture, agency, franchise, or employment relationship.</div>
        </div>
        <div className="flex gap-4">
          <div className="font-semibold text-cw-blue shrink-0 pt-0.5 w-8">17.8</div>
          <div className="leading-relaxed text-[14px]">Export Controls. You must not access or use the Platform in violation of any applicable export control or trade sanctions laws, including those administered by OFAC, BIS, or equivalent regulatory bodies in your jurisdiction.</div>
        </div>
      </div>
    )
  },
];
