import * as React from 'react';
import { BrandEmailLayout, brandColors } from './BrandEmailLayout.js';
import { BrandHeader } from './components/BrandHeader.js';
import { BrandFooter } from './components/BrandFooter.js';
import { BrandButton } from './components/BrandButton.js';

export interface AutoFixPrOpenedEmailProps {
  recipientName?: string;
  repoName: string;
  prNumber: number;
  prTitle: string;
  prUrl: string;
  agentId: string;
  runId: string | number;
  maxSeverity?: string | null;
  mode: 'auto' | 'manual';
  deadlineMinutes?: number;
  dashboardUrl?: string;
}

export const AutoFixPrOpenedEmail: React.FC<AutoFixPrOpenedEmailProps> = ({
  recipientName = 'Developer',
  repoName,
  prNumber,
  prTitle,
  prUrl,
  agentId,
  runId,
  maxSeverity = 'HIGH',
  mode,
  deadlineMinutes,
  dashboardUrl: customDashboardUrl,
}) => {
  const baseUrl = (process.env.FRONTEND_URL || 'https://www.codeward.cloud').replace(/^https?:\/\/codeward\.cloud/, 'https://www.codeward.cloud');
  const dashboardUrl = customDashboardUrl || `${baseUrl}/dashboard/livefeed?runId=${runId}`;
  const isAuto = mode === 'auto';

  return (
    <BrandEmailLayout previewText={`[Action Required] Auto-Fix PR #${prNumber} opened on ${repoName}`}>
      {/* 1. Header with Logo and Status */}
      <BrandHeader
        headline="Auto-Fix Pull Request Ready"
        subtitle={`${repoName} · Run #${runId}`}
        heroStat={{
          value: `PR #${prNumber}`,
          label: isAuto ? `Auto-Merge in ${deadlineMinutes ?? 10}m` : 'Manual Approval Required',
          valueColor: brandColors.textPrimary,
          labelColor: isAuto ? brandColors.warningYellow : brandColors.purpleAccent,
        }}
      />

      {/* 2. Intro Message */}
      <div style={messageBox}>
        <p style={leadText}>
          Hi <strong style={{ color: brandColors.textPrimary }}>{recipientName}</strong>,
        </p>
        <p style={bodyText}>
          Codeward's <strong style={{ color: brandColors.textPrimary }}>{agentId.replace('_', ' ')}</strong> agent detected issues on <code style={codeSnippet}>{repoName}</code> and generated an automated remediation pull request.
        </p>
      </div>

      {/* 3. Pull Request Detail Card */}
      <div style={detailBox}>
        <div style={detailRow}>
          <span style={detailLabel}>Pull Request:</span>
          <span style={detailValue}>#{prNumber} — {prTitle}</span>
        </div>
        <div style={detailRow}>
          <span style={detailLabel}>Generated By:</span>
          <span style={detailValue}>{agentId.toUpperCase()} Agent</span>
        </div>
        <div style={detailRow}>
          <span style={detailLabel}>Highest Severity:</span>
          <span style={{ ...detailValue, color: brandColors.dangerRed, fontWeight: 700 }}>
            {String(maxSeverity || 'HIGH').toUpperCase()}
          </span>
        </div>
        <div style={detailRow}>
          <span style={detailLabel}>Merge Policy:</span>
          <span style={detailValue}>
            {isAuto ? `Auto-merge with ${deadlineMinutes}m review window` : 'Manual approval mandated'}
          </span>
        </div>
      </div>

      {/* 4. Action Button */}
      <BrandButton href={dashboardUrl}>
        Review Diff & Approve on Codeward →
      </BrandButton>

      {/* 5. GitHub direct link */}
      <div style={secondaryLinkWrapper}>
        <a href={prUrl} style={secondaryLink} target="_blank" rel="noreferrer">
          View PR #{prNumber} directly on GitHub ↗
        </a>
      </div>

      {/* 6. Footer */}
      <BrandFooter
        recipientName={recipientName}
        purposeText={`Automated remediation notification for repository ${repoName}.`}
        isMandatoryTransactional={true}
      />
    </BrandEmailLayout>
  );
};

const messageBox: React.CSSProperties = {
  textAlign: 'center',
  marginBottom: '20px',
};

const leadText: React.CSSProperties = {
  fontSize: '15px',
  color: brandColors.textPrimary,
  margin: '0 0 8px 0',
};

const bodyText: React.CSSProperties = {
  fontSize: '13px',
  color: brandColors.textSecondary,
  lineHeight: '1.6',
  margin: '0',
};

const codeSnippet: React.CSSProperties = {
  fontFamily: 'monospace',
  fontSize: '12px',
  backgroundColor: '#f3f4f6',
  padding: '2px 6px',
  borderRadius: '4px',
  border: '1px solid #e5e7eb',
  color: brandColors.textPrimary,
};

const detailBox: React.CSSProperties = {
  backgroundColor: '#F9FAFB',
  border: '1px solid #E5E7EB',
  borderRadius: '12px',
  padding: '16px 20px',
  margin: '20px 0 24px 0',
};

const detailRow: React.CSSProperties = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  padding: '6px 0',
  fontSize: '13px',
  borderBottom: '1px solid #F3F4F6',
};

const detailLabel: React.CSSProperties = {
  color: brandColors.textSecondary,
  fontWeight: 600,
};

const detailValue: React.CSSProperties = {
  color: brandColors.textPrimary,
  fontWeight: 500,
  textAlign: 'right',
  maxWidth: '300px',
};

const secondaryLinkWrapper: React.CSSProperties = {
  textAlign: 'center',
  marginTop: '16px',
  marginBottom: '24px',
};

const secondaryLink: React.CSSProperties = {
  fontSize: '13px',
  color: brandColors.noticeBlue,
  textDecoration: 'none',
  fontWeight: 500,
};
